import type { ComponentType, SVGProps } from "react"
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiDocker,
  SiSupabase,
  SiN8N,
  SiGit,
  SiGithub,
  SiNetlify,
} from "react-icons/si"
import { Webhook, Sparkles } from "lucide-react"

export const skillIcons: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  HTML: SiHtml5,
  CSS: SiCss,
  JavaScript: SiJavascript,
  React: SiReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  "API REST": Webhook,
  "REST API": Webhook,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  Docker: SiDocker,
  Supabase: SiSupabase,
  n8n: SiN8N,
  "Fluxos com IA": Sparkles,
  "AI-assisted flows": Sparkles,
  Git: SiGit,
  GitHub: SiGithub,
  Netlify: SiNetlify,
}
